config/routes.rb
PATS67272::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  # Authentication routes
  match 'user/edit' => 'users#edit', :as => :edit_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login
  resources :sessions
  resources :users
  
  # Generated model routes
  resources :owners do
    resources :notes
  end

  resources :animals

  resources :pets do
    resources :notes
  end

  resources :visits do
    resources :notes
  end

  resources :procedures
  resources :medicine_costs
  resources :procedure_costs
  resources :animal_medicines

  resources :notes do
    resources :notes
  end
  resources :medicines


  # Semi-static page routes
  match 'home' => 'home#index', :as => :home
  match 'about' => 'home#about', :as => :about
  match 'contact' => 'home#contact', :as => :contact
  match 'privacy' => 'home#privacy', :as => :privacy
  match 'search' => 'home#search', :as => :search
  match 'medicines_search' => 'medicines#search', :as => :medicines_search
  
  # Set the root url
  root :to => 'home#index'
end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_by_medicine, :against => :description, :using => {:tsearch => {:prefix => true, :any_word => true, :dictionary => "english"}}

  # Relationships
  # -----------------------------
  has_many :animal_medicines
  has_many :animals, :through => :animal_medicines
  has_many :medicine_costs
  has_many :visit_medicines
  has_many :visits, :through => :vist_medicines

  # Scopes
  # -----------------------------
  scope :alphabetical, order('name')
  scope :depleted, where('stock_amount = ?', 0)
  scope :vaccines, where('vaccine = ?', true)
  scope :nonvaccines, where('vaccine = ?', false)
  
  # Validations
  # -----------------------------
  validates_presence_of :name
  validates_numericality_of :stock_amount, :only_integer => true, :greater_than_or_equal_to => 0
  
  # Other methods
  # -----------------------------
  def is_vaccine?
    vaccine
  end
  
  def current_cost_per_unit
    curr_cost_of_medicine = self.medicine_costs.current
    return nil if curr_cost_of_medicine.empty?
    curr_cost_of_medicine.first.cost_per_unit
  end
  
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController

  def index
    # finding all the active medicines and paginating that list (will_paginate)
    @medicines = Medicine.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def show
    @medicine = Medicine.find(params[:id])
    # get all the pets for this medicine
    @for_animals = @medicine.animals.alphabetical.all
  end

  def new
    @medicine = Medicine.new
  end

  def edit
    @medicine = Medicine.find(params[:id])
  end

  def create
    @medicine = Medicine.new(params[:medicine])
    if @medicine.save
      # if saved to database
      flash[:notice] = "Successfully created #{@medicine.name}."
      redirect_to @medicine # go to show medicine page
    else
      # return to the 'new' form
      render :action => 'new'
    end
  end

  def update
    @medicine = Medicine.find(params[:id])
    if @medicine.update_attributes(params[:medicine])
      flash[:notice] = "Successfully updated #{@medicine.name}."
      redirect_to @medicine
    else
      render :action => 'edit'
    end
  end

  def search
    @query = params[:query]
    @medicines = Medicine.search_by_medicine(@query)
    @total_medicine_hits = @medicines.size
  end

  def destroy
    @medicine = Medicine.find(params[:id])
    @medicine.destroy
    flash[:notice] = "Successfully removed #{@medicine.name} from the PATS system."
    redirect_to medicines_url
  end
end

app/views/medicines/_for_animals.html.erb
<h2>For Animals:</h2>
<table class="datagrid">
  <thead class="datagrid">
    <th width="90">&nbsp;</th>
  </thead>
  
<% for animal in @for_animals %>
  <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
    <td align="left">&nbsp;<%= link_to animal.name, animal_path(animal) %></td>
  </tr>
<% end %>
</table>
<p class="supertiny">&nbsp;</p>

app/views/medicines/_form.html.erb
<%= form_for(@medicine) do |f| %>
  <% if @medicine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

      <ul>
      <% @medicine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :method %><br />
    <%= f.text_field :method %>
  </div>
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :stock_amount %><br />
    <%= f.text_field :stock_amount %>
  </div>
  <div class="field">
    <%= f.label :vaccine %><br />
    <%= f.check_box :vaccine %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicines/_medicine_data.html.erb
<h2>Medicine Information:</h2>
<b>Name:&nbsp;&nbsp;</b><br>
  <%= @medicine.name %><br /><br />

<b>Description:&nbsp;&nbsp;</b><br>
  <%= @medicine.description %><br><br />
  
<b>Method:&nbsp;&nbsp;</b><br>
  <%= @medicine.method %><br><br />
    
<b>Unit Type:&nbsp;&nbsp;</b><br>
  <%= @medicine.unit %><br><br />

<b>Units in stock:&nbsp;&nbsp;</b><br>
  <%= @medicine.stock_amount %><br /><br />
  
<b>Vaccine?&nbsp;&nbsp;</b><br>
  <%= (@medicine.vaccine ? "Yes" : "No") %><br /><br />

app/views/medicines/edit.html.erb
<h1>Editing medicine</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicine %> |
<%= link_to 'Back', medicines_path %>

app/views/medicines/index.html.erb
<%= form_tag(medicines_search_path) do %>
  <%= text_field_tag('query', '', :size => 12) %>
  <%= submit_tag('Find') %>
<% end %> 
<br>
<br>

<h1>Medicines offered by PATS</h1><br>

<table class="datagrid">
  <thead class="datagrid">
    <th>Medicine</th>
    <th>Method</th>
		<th>Unit Type</th>
		<th>Units Available</th>
		<th>&nbsp;</th>
  </thead>
  <% for medicine in @medicines %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to "#{medicine.name}", medicine_path(medicine) %></td>
      <td><%= medicine.method %></td>
      <td><%= medicine.unit %></td>
      <td><%= medicine.stock_amount %></td>
	  	<td align="center">
				<%= link_to(image_tag("icons/edit_dg.gif", :border => 0), edit_medicine_path(medicine))  %>
				<%= link_to(image_tag("icons/delete_dg.gif", :border => 0), medicine_path(medicine), :confirm => 'Are you sure you wish to delete this information?', :method => :delete) %>
	  	</td>
    </tr>
  <% end %>
</table>
<p class="supertiny"></p>

<!-- Add the pagination using will_paginate gem -->
<span class="smtext">
<%= will_paginate @medicine, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

<p><strong><%= link_to "Add A New Medicine", new_medicine_path %></strong></p>

app/views/medicines/new.html.erb
<h1>New medicine</h1>

<%= render 'form' %>

<%= link_to 'Back', medicines_path %>

app/views/medicines/search.html.erb
<h2>Search result for description <em>'<%= @query %>'</em> resulted in <%= pluralize(@total_medicine_hits, 'hit') %></h2>
<p class="supertiny">&nbsp;</p>

<% unless @medicines.empty? %>
	<p><em><strong>Medicines matching description '<%= @query %>'</strong></em></p>
	<ul>
		<% for medicine in @medicines do %>
			<li><%= link_to medicine.name, medicine_path(medicine) %></li>
		<% end %>
	</ul>
	<p class="smtext">&nbsp;</p>
<% end %>

app/views/medicines/show.html.erb
<table>
	<tr valign="top">	
		<td width="300">
			<%= render :partial => "medicine_data" %>
		</td>
		<td width="10">&nbsp;</td>
		<td width="250">
			<% unless @for_animals.empty? %>
			  <%= render :partial => "for_animals" %>
			<% end %>
		</td>
	</tr>
</table>
<p class="smtext">&nbsp;</p>
<p>&nbsp;
  <%= link_to "Edit", edit_medicine_path(@medicine) %> |
  <%= link_to "Destroy", @medicine, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", medicines_path %>
</p>